import type { CookingRecipe } from './recipeTypes';

const I = (name: string, amount?: number, unit?: string) =>
  amount != null ? `${name} — ${amount}${unit ? ` ${unit}` : ''}` : name;

/** Additional diaspora favourites beyond the original 24-recipe library. */
export const AFRO_CARIBBEAN_EXTRA: CookingRecipe[] = [
  {
    id: 'ackee-saltfish',
    title: 'Ackee & Saltfish',
    description: 'Jamaica’s national breakfast — savoury, buttery ackee with cured cod',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&q=80',
    minutes: 35,
    prepMinutes: 20,
    servings: 4,
    difficulty: 'Medium',
    tags: ['caribbean', 'jamaican', 'breakfast', 'fish', 'high-protein', 'west-african'],
    ingredients: [
      I('Salt cod', 300, 'g'),
      I('Tinned ackee', 540, 'g'),
      I('Scotch bonnet', 0.5, 'whole'),
      I('Bell pepper', 1, 'whole'),
      I('Tomato', 2, 'whole'),
      I('Spring onion', 4, 'whole'),
      I('Thyme sprigs', 4, 'whole'),
      I('Black pepper', 0.5, 'tsp'),
      I('Vegetable oil', 2, 'tbsp'),
    ],
    steps: [
      'Soak saltfish overnight or boil 20 min, change water twice, flake',
      'Drain ackee gently; pat dry',
      'Sauté peppers, tomato, spring onion & thyme until soft',
      'Fold in saltfish, then ackee; heat through without mashing',
      'Season with black pepper; serve with fried dumpling or breadfruit',
    ],
    stepTimers: [1200, null, 480, 180, null],
    nutrition: { calories: 320, protein: 28, carbs: 18, fat: 14 },
    category: 'breakfast',
    rating: 4.8,
  },
  {
    id: 'jamaican-beef-patty',
    title: 'Jamaican Beef Patties',
    description: 'Flaky turmeric pastry with spiced mince filling',
    image: 'https://images.unsplash.com/photo-1565299585323-38174c0b5e47?w=600&q=80',
    minutes: 90,
    prepMinutes: 50,
    servings: 8,
    difficulty: 'Medium',
    tags: ['caribbean', 'jamaican', 'street-food', 'batch', 'comfort', 'high-protein'],
    ingredients: [
      I('Plain flour', 400, 'g'),
      I('Curry powder', 1, 'tbsp'),
      I('Turmeric', 1, 'tsp'),
      I('Cold butter', 120, 'g'),
      I('Beef mince', 500, 'g'),
      I('Onion', 1, 'whole'),
      I('Scotch bonnet', 0.5, 'whole'),
      I('Fresh thyme', 1, 'tbsp'),
      I('Beef stock', 150, 'ml'),
      I('Breadcrumbs', 2, 'tbsp'),
    ],
    steps: [
      'Rub flour with butter, curry & turmeric; bind with iced water, chill 30 min',
      'Brown mince; add onion, thyme, scotch bonnet, stock; simmer 15 min until thick',
      'Stir in breadcrumbs; cool completely',
      'Roll pastry thin, cut rounds, fill, crimp with fork',
      'Bake 200°C / 400°F 18–22 min until golden',
    ],
    stepTimers: [1800, 900, null, null, 1200],
    nutrition: { calories: 380, protein: 18, carbs: 32, fat: 20 },
    category: 'lunch',
    rating: 4.7,
  },
  {
    id: 'escovitch-fish',
    title: 'Escovitch Fish',
    description: 'Fried whole fish topped with hot pickled vegetables',
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=600&q=80',
    minutes: 45,
    prepMinutes: 20,
    servings: 4,
    difficulty: 'Medium',
    tags: ['caribbean', 'jamaican', 'fish', 'spicy', 'high-protein', 'pescatarian'],
    ingredients: [
      I('Whole snapper or sea bass', 2, 'whole'),
      I('Carrot', 1, 'whole'),
      I('Onion', 1, 'whole'),
      I('Scotch bonnet', 1, 'whole'),
      I('White vinegar', 200, 'ml'),
      I('Allspice berries', 6, 'whole'),
      I('Vegetable oil (for frying)', 500, 'ml'),
      I('Lime', 2, 'whole'),
    ],
    steps: [
      'Score fish, season with lime, salt & pepper 20 min',
      'Julienne carrot & onion; slice scotch bonnet',
      'Simmer vinegar with allspice, veg & pinch sugar 5 min; cool slightly',
      'Deep-fry fish until crisp & cooked through',
      'Spoon warm pickle over fish; rest 5 min before serving',
    ],
    stepTimers: [1200, null, 300, 600, 300],
    nutrition: { calories: 420, protein: 38, carbs: 14, fat: 24 },
    category: 'dinner',
    rating: 4.8,
  },
  {
    id: 'jamaican-oxtail-stew',
    title: 'Jamaican Oxtail Stew',
    description: 'Slow-braised tails in butter beans & rich gravy',
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=600&q=80',
    minutes: 200,
    prepMinutes: 25,
    servings: 6,
    difficulty: 'Hard',
    tags: ['caribbean', 'jamaican', 'stew', 'comfort', 'high-protein', 'batch'],
    ingredients: [
      I('Oxtail pieces', 1.5, 'kg'),
      I('Butter beans (tinned)', 400, 'g'),
      I('Beef stock', 800, 'ml'),
      I('Soy sauce', 2, 'tbsp'),
      I('Brown sugar', 1, 'tbsp'),
      I('Allspice', 0.5, 'tsp'),
      I('Scotch bonnet', 1, 'whole'),
      I('Spring onion', 3, 'whole'),
      I('Garlic', 4, 'cloves'),
      I('Thyme', 1, 'tbsp'),
    ],
    steps: [
      'Season oxtail; brown well in batches',
      'Deglaze with stock, soy & sugar; add aromatics & scotch bonnet whole',
      'Cover; braise low 2.5–3 hr until meat falls from bone',
      'Skim fat; stir in drained butter beans last 15 min',
      'Reduce gravy if needed; adjust salt',
    ],
    stepTimers: [null, null, 9000, 900, null],
    nutrition: { calories: 520, protein: 42, carbs: 22, fat: 28 },
    category: 'dinner',
    rating: 4.9,
  },
  {
    id: 'trinidadian-callaloo',
    title: 'Trinidadian Callaloo',
    description: 'Silky leafy stew with coconut milk & crab (optional)',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&q=80',
    minutes: 50,
    prepMinutes: 15,
    servings: 6,
    difficulty: 'Easy',
    tags: ['caribbean', 'trinidadian', 'vegetarian', 'plant-based', 'stew', 'healthy'],
    ingredients: [
      I('Dasheen or spinach leaves', 400, 'g'),
      I('Okra', 150, 'g'),
      I('Coconut milk', 400, 'ml'),
      I('Pumpkin', 200, 'g'),
      I('Onion', 1, 'whole'),
      I('Garlic', 4, 'cloves'),
      I('Thyme', 1, 'tbsp'),
      I('Scotch bonnet', 0.5, 'whole'),
      I('Crab claws (optional)', 4, 'whole'),
    ],
    steps: [
      'Wash & strip tough stems from greens',
      'Simmer pumpkin, onion, garlic & okra in coconut milk 15 min',
      'Add greens & thyme; cook 20 min until very tender',
      'Blend with stick blender to silky soup (or use traditional swizzle)',
      'Add crab if using; simmer 8 min; remove scotch bonnet before serving',
    ],
    stepTimers: [null, 900, 1200, null, 480],
    nutrition: { calories: 210, protein: 8, carbs: 22, fat: 11 },
    category: 'dinner',
    rating: 4.6,
  },
  {
    id: 'barbados-cou-cou-flying-fish',
    title: 'Cou-Cou & Flying Fish',
    description: 'Cornmeal cou-cou with herbed flying fish stew',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600&q=80',
    minutes: 55,
    prepMinutes: 20,
    servings: 4,
    difficulty: 'Medium',
    tags: ['caribbean', 'barbadian', 'fish', 'comfort', 'pescatarian'],
    ingredients: [
      I('Flying fish or tilapia fillets', 500, 'g'),
      I('Fine cornmeal', 200, 'g'),
      I('Okra', 200, 'g'),
      I('Onion', 2, 'whole'),
      I('Tomato', 3, 'whole'),
      I('Thyme', 1, 'tbsp'),
      I('Butter', 40, 'g'),
      I('Fish stock', 800, 'ml'),
      I('Lime', 1, 'whole'),
    ],
    steps: [
      'Stew fish with onion, tomato, thyme & stock 12 min; finish with lime',
      'Slice okra; simmer half in 400ml water 8 min',
      'Whisk cornmeal into okra liquid; stir constantly 10 min until thick cou-cou',
      'Fold in butter & remaining okra rounds',
      'Serve cou-cou topped with fish & gravy',
    ],
    stepTimers: [720, 480, 600, null, null],
    nutrition: { calories: 380, protein: 28, carbs: 48, fat: 10 },
    category: 'dinner',
    rating: 4.5,
  },
  {
    id: 'haitian-griot',
    title: 'Haitian Griot',
    description: 'Citrus-marinated pork, twice-cooked until crisp',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&q=80',
    minutes: 140,
    prepMinutes: 30,
    servings: 6,
    difficulty: 'Medium',
    tags: ['caribbean', 'haitian', 'high-protein', 'comfort', 'batch'],
    ingredients: [
      I('Pork shoulder (cubed)', 1.2, 'kg'),
      I('Sour orange or lime juice', 120, 'ml'),
      I('Epis seasoning blend', 4, 'tbsp'),
      I('Scotch bonnet', 1, 'whole'),
      I('Bell pepper', 1, 'whole'),
      I('Garlic', 6, 'cloves'),
      I('Thyme', 1, 'tbsp'),
      I('Vegetable oil', 400, 'ml'),
    ],
    steps: [
      'Marinate pork in citrus, epis, garlic, pepper & thyme 4–24 hr',
      'Cover with water, simmer 60–90 min until tender & liquid nearly gone',
      'Reduce remaining liquid until sticky on pork',
      'Deep-fry or shallow-fry in batches until deep golden & crisp',
      'Drain; serve with pikliz',
    ],
    stepTimers: [14400, 5400, 600, 480, null],
    nutrition: { calories: 480, protein: 36, carbs: 6, fat: 34 },
    category: 'dinner',
    rating: 4.8,
  },
];
