import type { CookingRecipe } from './recipeTypes';

const I = (name: string, amount?: number, unit?: string) =>
  amount != null ? `${name} — ${amount}${unit ? ` ${unit}` : ''}` : name;

export const LEGACY_PART_C: CookingRecipe[] = [
  {
    id: 'trini-curry-goat',
    title: 'Trini Curry Goat',
    description: 'Slow-braised island favourite',
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=600&q=80',
    minutes: 140,
    prepMinutes: 20,
    servings: 4,
    difficulty: 'Medium',
    tags: ['caribbean', 'trinidadian', 'curry', 'high-protein', 'spicy'],
    ingredients: [
      I('Goat shoulder (cubed)', 1, 'kg'),
      I('Caribbean curry powder', 4, 'tbsp'),
      I('Garlic cloves', 6, 'cloves'),
      I('Fresh ginger', 1, 'tbsp'),
      I('Onion', 2, 'whole'),
      I('Scotch bonnet pepper', 1, 'whole'),
      I('Fresh thyme', 1, 'tbsp'),
      I('Lime', 2, 'whole'),
      I('Coconut oil', 3, 'tbsp'),
    ],
    steps: [
      'Wash goat with lime, season with garlic, ginger, thyme, half the curry powder, marinate 1 hr',
      'Heat oil, bloom remaining curry powder 2 min until fragrant',
      'Add goat, sear 5 min, add onion & scotch bonnet',
      'Pour in 700ml water, cover & simmer low 90 min until tender',
      'Uncover last 15 min to thicken sauce, serve with roti',
    ],
    stepTimers: [3600, 120, 300, 5400, 900],
    nutrition: { calories: 560, protein: 48, carbs: 14, fat: 34 },
    category: 'dinner',
    rating: 4.8,
  },
  {
    id: 'plantain-black-bean-bowl',
    title: 'Plantain & Black Bean Bowl',
    description: 'Sweet, savoury & wholesome',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&q=80',
    minutes: 30,
    prepMinutes: 10,
    servings: 2,
    difficulty: 'Easy',
    tags: ['caribbean', 'african', 'vegetarian', 'plant-based', 'quick', 'whole-foods', 'lunch'],
    ingredients: [
      I('Ripe plantains', 2, 'whole'),
      I('Black beans (tinned)', 400, 'g'),
      I('Brown rice (cooked)', 200, 'g'),
      I('Avocado', 1, 'whole'),
      I('Lime', 1, 'whole'),
      I('Smoked paprika', 1, 'tsp'),
      I('Garlic cloves', 2, 'cloves'),
      I('Coconut oil', 2, 'tbsp'),
      I('Fresh coriander', 1, 'handful'),
    ],
    steps: [
      'Slice plantains diagonally, fry in coconut oil 3 min per side until caramelised',
      'Sauté garlic, add black beans with liquid, paprika, simmer 5 min, mash slightly',
      'Warm brown rice, divide between bowls',
      'Top with beans, plantain, sliced avocado',
      'Squeeze lime, scatter coriander & serve',
    ],
    stepTimers: [360, 300, null, null, null],
    nutrition: { calories: 420, protein: 14, carbs: 70, fat: 11 },
    category: 'lunch',
    rating: 4.6,
  },
  {
    id: 'greek-yoghurt-chicken-salad',
    title: 'Greek Yoghurt Chicken Salad',
    description: 'Creamy, high-protein and light',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&q=80',
    minutes: 20,
    prepMinutes: 10,
    servings: 2,
    difficulty: 'Easy',
    tags: ['low-calorie', 'high-protein', 'healthy', 'quick', 'mediterranean', 'lunch'],
    ingredients: [
      I('Cooked chicken breast', 260, 'g'),
      I('Greek yoghurt', 120, 'g'),
      I('Celery', 2, 'stalks'),
      I('Red onion', 0.25, 'whole'),
      I('Dijon mustard', 1, 'tsp'),
      I('Lemon juice', 1, 'tbsp'),
    ],
    steps: ['Shred chicken', 'Mix yoghurt, mustard and lemon', 'Fold in chopped veg and chicken', 'Season and chill 5 min'],
    stepTimers: [null, null, null, 300],
    nutrition: { calories: 240, protein: 30, carbs: 9, fat: 8 },
    category: 'lunch',
    rating: 4.7,
  },
  {
    id: 'lemon-herb-cod-parcels',
    title: 'Lemon Herb Cod Parcels',
    description: 'Steamed fish with bright citrus',
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=600&q=80',
    minutes: 28,
    prepMinutes: 10,
    servings: 2,
    difficulty: 'Easy',
    tags: ['low-calorie', 'fish', 'high-protein', 'mediterranean', 'whole-foods', 'pescatarian'],
    ingredients: [
      I('Cod fillets', 2, 'fillets'),
      I('Lemon', 1, 'whole'),
      I('Asparagus', 180, 'g'),
      I('Parsley', 2, 'tbsp'),
      I('Olive oil', 1, 'tbsp'),
    ],
    steps: ['Preheat oven 200°C', 'Wrap cod, asparagus, lemon and herbs in foil', 'Bake 15-18 min', 'Serve with pan juices'],
    stepTimers: [null, null, 1080, null],
    nutrition: { calories: 230, protein: 33, carbs: 7, fat: 7 },
    category: 'healthy',
    rating: 4.8,
  },
  {
    id: 'tomato-basil-egg-white-omelette',
    title: 'Tomato Basil Egg White Omelette',
    description: 'Lean breakfast with fresh herbs',
    image: 'https://images.unsplash.com/photo-1510693206972-df098062cb71?w=600&q=80',
    minutes: 12,
    prepMinutes: 5,
    servings: 1,
    difficulty: 'Easy',
    tags: ['low-calorie', 'high-protein', 'quick', 'healthy', 'low-carb', 'breakfast'],
    ingredients: [
      I('Egg whites', 180, 'ml'),
      I('Cherry tomatoes', 80, 'g'),
      I('Fresh basil', 1, 'tbsp'),
      I('Olive oil spray', 1, 'tsp'),
    ],
    steps: ['Whisk egg whites', 'Cook tomatoes 1 min', 'Pour whites and set', 'Fold with basil'],
    stepTimers: [null, 60, null, null],
    nutrition: { calories: 170, protein: 20, carbs: 6, fat: 6 },
    category: 'breakfast',
    rating: 4.4,
  },
  {
    id: 'spicy-lentil-soup-legacy',
    title: 'Spicy Lentil Soup',
    description: 'Filling bowl under 300 calories',
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80',
    minutes: 35,
    prepMinutes: 10,
    servings: 4,
    difficulty: 'Easy',
    tags: ['low-calorie', 'plant-based', 'vegetarian', 'healthy', 'whole-foods'],
    ingredients: [
      I('Red lentils', 220, 'g'),
      I('Carrots', 2, 'whole'),
      I('Onion', 1, 'whole'),
      I('Vegetable stock', 1.2, 'l'),
      I('Cumin', 1, 'tsp'),
    ],
    steps: ['Saute onion and carrot', 'Add lentils, cumin and stock', 'Simmer 20 min', 'Blend half for creaminess'],
    stepTimers: [null, null, 1200, null],
    nutrition: { calories: 220, protein: 13, carbs: 31, fat: 5 },
    category: 'healthy',
    rating: 4.7,
  },
  {
    id: 'chicken-broccoli-stir-fry-legacy',
    title: 'Chicken & Broccoli Stir-Fry',
    description: 'Weeknight classic made lighter',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&q=80',
    minutes: 24,
    prepMinutes: 10,
    servings: 2,
    difficulty: 'Easy',
    tags: ['low-calorie', 'high-protein', 'quick', 'healthy', 'whole-foods', 'asian'],
    ingredients: [
      I('Chicken breast', 300, 'g'),
      I('Broccoli florets', 250, 'g'),
      I('Low-sodium soy sauce', 1, 'tbsp'),
      I('Garlic cloves', 2, 'cloves'),
      I('Sesame oil', 1, 'tsp'),
    ],
    steps: ['Sear chicken strips', 'Add broccoli and a splash of water', 'Add garlic and soy', 'Finish with sesame oil'],
    stepTimers: [300, 300, null, null],
    nutrition: { calories: 285, protein: 34, carbs: 16, fat: 9 },
    category: 'dinner',
    rating: 4.7,
  },
  {
    id: 'cauliflower-rice-burrito-bowl',
    title: 'Cauliflower Rice Burrito Bowl',
    description: 'Mexican-style bowl, lower carbs',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80',
    minutes: 25,
    prepMinutes: 10,
    servings: 2,
    difficulty: 'Easy',
    tags: ['low-calorie', 'low-carb', 'healthy', 'quick', 'vegetarian', 'mexican'],
    ingredients: [
      I('Cauliflower rice', 300, 'g'),
      I('Black beans', 180, 'g'),
      I('Sweetcorn', 100, 'g'),
      I('Tomato salsa', 120, 'g'),
      I('Avocado', 0.5, 'whole'),
    ],
    steps: ['Cook cauliflower rice 4 min', 'Warm beans and sweetcorn', 'Assemble with salsa and avocado'],
    stepTimers: [240, null, null],
    nutrition: { calories: 270, protein: 17, carbs: 22, fat: 12 },
    category: 'dinner',
    rating: 4.5,
  },
];
