import type { CookingRecipe } from './recipeTypes';

const I = (name: string, amount?: number, unit?: string) =>
  amount != null ? `${name} — ${amount}${unit ? ` ${unit}` : ''}` : name;

export const LEGACY_PART_B: CookingRecipe[] = [
  {
    id: 'jamaican-jerk-chicken',
    title: 'Jamaican Jerk Chicken',
    description: 'Smoky, spicy island classic',
    image: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=600&q=80',
    minutes: 55,
    prepMinutes: 20,
    servings: 4,
    difficulty: 'Medium',
    tags: ['caribbean', 'jamaican', 'spicy', 'high-protein', 'grill', 'west-african'],
    ingredients: [
      I('Chicken thighs', 8, 'whole'),
      I('Scotch bonnet pepper', 1, 'whole'),
      I('Spring onions', 4, 'whole'),
      I('Garlic cloves', 4, 'cloves'),
      I('Fresh thyme', 2, 'tbsp'),
      I('Allspice (ground)', 1, 'tbsp'),
      I('Brown sugar', 2, 'tbsp'),
      I('Soy sauce', 3, 'tbsp'),
      I('Lime', 2, 'whole'),
      I('Ground cinnamon', 0.5, 'tsp'),
    ],
    steps: [
      'Blend scotch bonnet, spring onions, garlic, thyme, allspice, sugar, soy & lime into marinade',
      'Coat chicken, marinate at least 2 hours (overnight is best)',
      'Preheat grill or oven to 200°C / 400°F',
      'Grill chicken 25-30 min, turning, until charred & cooked through',
      'Rest 5 min, squeeze fresh lime & serve with rice & peas',
    ],
    stepTimers: [null, 7200, null, 1800, 300],
    nutrition: { calories: 460, protein: 42, carbs: 14, fat: 26 },
    category: 'dinner',
    rating: 4.9,
  },
  {
    id: 'caribbean-rice-and-peas',
    title: 'Caribbean Rice & Peas',
    description: 'Coconut-infused side staple',
    image: 'https://images.unsplash.com/photo-1516684732162-798a0062be99?w=600&q=80',
    minutes: 50,
    prepMinutes: 10,
    servings: 4,
    difficulty: 'Easy',
    tags: ['caribbean', 'jamaican', 'vegetarian', 'plant-based', 'side', 'nigerian'],
    ingredients: [
      I('Long grain rice', 300, 'g'),
      I('Kidney beans (tinned)', 400, 'g'),
      I('Coconut milk', 400, 'ml'),
      I('Spring onions', 3, 'whole'),
      I('Garlic cloves', 3, 'cloves'),
      I('Fresh thyme', 1, 'tbsp'),
      I('Scotch bonnet pepper', 1, 'whole'),
      I('Allspice berries', 4, 'whole'),
    ],
    steps: [
      'Sauté garlic & spring onions in a pot 2 min',
      'Add coconut milk, beans (with liquid), thyme, allspice & whole scotch bonnet',
      'Bring to boil, stir in rinsed rice & 200ml water',
      'Reduce heat, cover & simmer 25 min until liquid absorbed',
      'Remove scotch bonnet, fluff with fork & serve',
    ],
    stepTimers: [120, null, null, 1500, null],
    nutrition: { calories: 380, protein: 11, carbs: 62, fat: 10 },
    category: 'dinner',
    rating: 4.7,
  },
  {
    id: 'trinidadian-doubles',
    title: 'Trinidadian Doubles',
    description: 'Fluffy bara with curried chickpeas',
    image: 'https://images.unsplash.com/photo-1631292784640-2b24be784d5d?w=600&q=80',
    minutes: 120,
    prepMinutes: 90,
    servings: 4,
    difficulty: 'Medium',
    tags: ['caribbean', 'trinidadian', 'vegetarian', 'street-food', 'lunch'],
    ingredients: [
      I('Plain flour', 250, 'g'),
      I('Ground turmeric', 1, 'tsp'),
      I('Instant yeast', 1, 'tsp'),
      I('Chickpeas (tinned)', 800, 'g'),
      I('Curry powder', 2, 'tbsp'),
      I('Onion', 1, 'whole'),
      I('Garlic cloves', 3, 'cloves'),
      I('Scotch bonnet pepper', 1, 'whole'),
      I('Fresh coriander', 1, 'handful'),
    ],
    steps: [
      'Mix flour, turmeric, yeast, salt & 180ml warm water into soft dough, rest 1-2 hr',
      'Sauté onion & garlic, add curry powder, bloom 1 min',
      'Add chickpeas with liquid, simmer 15 min until thickened',
      'Heat oil, fry small flattened dough rounds 30 sec per side until puffed',
      'Top each bara with curried chickpeas, scotch bonnet & coriander',
    ],
    stepTimers: [5400, 60, 900, 60, null],
    nutrition: { calories: 410, protein: 14, carbs: 58, fat: 14 },
    category: 'lunch',
    rating: 4.8,
  },
  {
    id: 'nigerian-jollof-rice',
    title: 'Nigerian Jollof Rice',
    description: 'Smoky tomato-pepper one pot',
    image: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=600&q=80',
    minutes: 60,
    prepMinutes: 15,
    servings: 6,
    difficulty: 'Medium',
    tags: ['african', 'nigerian', 'west-african', 'one-pot', 'spicy', 'jollof'],
    ingredients: [
      I('Long grain rice', 500, 'g'),
      I('Plum tomatoes', 6, 'whole'),
      I('Red bell peppers', 2, 'whole'),
      I('Scotch bonnet pepper', 1, 'whole'),
      I('Onion', 2, 'whole'),
      I('Tomato puree', 3, 'tbsp'),
      I('Vegetable oil', 4, 'tbsp'),
      I('Bay leaves', 2, 'whole'),
      I('Curry powder', 1, 'tbsp'),
      I('Dried thyme', 1, 'tsp'),
    ],
    steps: [
      'Blend tomatoes, peppers, scotch bonnet & 1 onion until smooth',
      'Fry chopped onion in oil 3 min, add tomato puree, fry 5 min',
      'Pour in blended sauce, simmer 15 min until oil rises',
      'Add curry, thyme, bay & 500ml stock, season well',
      'Stir in rinsed rice, cover tightly & cook on low 25 min until tender',
    ],
    stepTimers: [null, 480, 900, null, 1500],
    nutrition: { calories: 430, protein: 9, carbs: 72, fat: 12 },
    category: 'dinner',
    rating: 4.9,
  },
  {
    id: 'ethiopian-doro-wat',
    title: 'Ethiopian Doro Wat',
    description: 'Rich berbere chicken stew',
    image: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=600&q=80',
    minutes: 80,
    prepMinutes: 20,
    servings: 4,
    difficulty: 'Hard',
    tags: ['african', 'ethiopian', 'spicy', 'stew', 'high-protein'],
    ingredients: [
      I('Chicken legs', 6, 'whole'),
      I('Red onions', 4, 'whole'),
      I('Berbere spice', 3, 'tbsp'),
      I('Niter kibbeh or ghee', 4, 'tbsp'),
      I('Garlic cloves', 5, 'cloves'),
      I('Fresh ginger', 1, 'tbsp'),
      I('Tomato puree', 2, 'tbsp'),
      I('Lemon', 1, 'whole'),
      I('Hard-boiled eggs', 4, 'whole'),
    ],
    steps: [
      'Marinate chicken in lemon juice & salt 30 min',
      'Slowly cook finely chopped onions dry in pot 20 min until jammy',
      'Add ghee, garlic, ginger & berbere, cook 5 min',
      'Add chicken & tomato puree, pour in 250ml water, simmer 30 min',
      'Score eggs, add to stew last 10 min, serve with injera',
    ],
    stepTimers: [1800, 1200, 300, 1800, 600],
    nutrition: { calories: 520, protein: 38, carbs: 18, fat: 32 },
    category: 'dinner',
    rating: 4.8,
  },
  {
    id: 'moroccan-chicken-tagine',
    title: 'Moroccan Chicken Tagine',
    description: 'Sweet & savoury slow-cooked',
    image: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?w=600&q=80',
    minutes: 75,
    prepMinutes: 15,
    servings: 4,
    difficulty: 'Medium',
    tags: ['african', 'moroccan', 'north-african', 'mediterranean', 'high-protein'],
    ingredients: [
      I('Chicken thighs', 8, 'whole'),
      I('Onion', 2, 'whole'),
      I('Preserved lemon', 1, 'whole'),
      I('Green olives', 100, 'g'),
      I('Ras el hanout', 2, 'tbsp'),
      I('Ground ginger', 1, 'tsp'),
      I('Saffron threads', 1, 'pinch'),
      I('Garlic cloves', 4, 'cloves'),
      I('Fresh coriander', 1, 'handful'),
      I('Olive oil', 3, 'tbsp'),
    ],
    steps: [
      'Rub chicken with ras el hanout, ginger, salt & olive oil',
      'Brown chicken in tagine or heavy pot 5 min per side',
      'Add onions & garlic, soften 5 min',
      'Add saffron, 250ml water, preserved lemon & olives, cover',
      'Simmer low 45 min, top with coriander before serving',
    ],
    stepTimers: [null, 600, 300, null, 2700],
    nutrition: { calories: 470, protein: 36, carbs: 32, fat: 20 },
    category: 'dinner',
    rating: 4.8,
  },
  {
    id: 'west-african-peanut-stew',
    title: 'West African Peanut Stew',
    description: 'Creamy, nutty & warming',
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80',
    minutes: 55,
    prepMinutes: 15,
    servings: 4,
    difficulty: 'Easy',
    tags: ['african', 'west-african', 'vegetarian', 'plant-based', 'stew', 'healthy'],
    ingredients: [
      I('Sweet potatoes', 2, 'whole'),
      I('Onion', 1, 'whole'),
      I('Garlic cloves', 3, 'cloves'),
      I('Fresh ginger', 1, 'tbsp'),
      I('Tomato puree', 3, 'tbsp'),
      I('Smooth peanut butter', 150, 'g'),
      I('Vegetable stock', 700, 'ml'),
      I('Kale', 150, 'g'),
      I('Cayenne pepper', 0.5, 'tsp'),
    ],
    steps: [
      'Sauté onion, garlic & ginger in oil 3 min',
      'Add tomato puree & cayenne, cook 2 min',
      'Stir in cubed sweet potato & stock, simmer 20 min',
      'Whisk in peanut butter until creamy',
      'Add chopped kale last 5 min, season & serve over rice',
    ],
    stepTimers: [180, 120, 1200, null, 300],
    nutrition: { calories: 440, protein: 16, carbs: 48, fat: 22 },
    category: 'dinner',
    rating: 4.7,
  },
  {
    id: 'south-african-bobotie',
    title: 'South African Bobotie',
    description: 'Spiced mince with custard top',
    image: 'https://images.unsplash.com/photo-1598511757337-fe2cafc31ba0?w=600&q=80',
    minutes: 70,
    prepMinutes: 20,
    servings: 6,
    difficulty: 'Medium',
    tags: ['african', 'south-african', 'comfort', 'high-protein'],
    ingredients: [
      I('Beef mince', 750, 'g'),
      I('Onion', 2, 'whole'),
      I('Curry powder', 2, 'tbsp'),
      I('Mango chutney', 3, 'tbsp'),
      I('Sultanas', 60, 'g'),
      I('White bread (slice)', 2, 'slices'),
      I('Milk', 250, 'ml'),
      I('Eggs', 2, 'whole'),
      I('Bay leaves', 4, 'whole'),
      I('Lemon zest', 1, 'tsp'),
    ],
    steps: [
      'Soak bread in 100ml milk, squeeze, reserve milk',
      'Sauté onion 5 min, add curry powder 1 min',
      'Add mince, brown 8 min, stir in chutney, sultanas, bread, lemon zest',
      'Press into baking dish, top with bay leaves',
      'Whisk eggs with remaining milk, pour over, bake 180°C / 350°F 30 min until set',
    ],
    stepTimers: [null, 360, 480, null, 1800],
    nutrition: { calories: 490, protein: 30, carbs: 24, fat: 28 },
    category: 'dinner',
    rating: 4.6,
  },
];
