import type { CookingRecipe } from './recipeTypes';

const I = (name: string, amount?: number, unit?: string) =>
  amount != null ? `${name} — ${amount}${unit ? ` ${unit}` : ''}` : name;

export const LEGACY_PART_A: CookingRecipe[] = [
  {
    id: 'creamy-tuscan-chicken',
    title: 'Creamy Tuscan Chicken',
    description: 'Rich & flavourful one-pan dish',
    image: 'https://images.unsplash.com/photo-1518492104633-130d0cc84637?w=600&q=80',
    minutes: 35,
    prepMinutes: 10,
    servings: 4,
    difficulty: 'Easy',
    tags: ['one-pan', 'high-protein', 'italian', 'low-carb', 'dinner'],
    ingredients: [
      I('Chicken breast', 4, 'fillets'),
      I('Sun-dried tomatoes', 100, 'g'),
      I('Spinach', 150, 'g'),
      I('Garlic cloves', 3, 'cloves'),
      I('Heavy cream', 250, 'ml'),
      I('Parmesan', 50, 'g'),
      I('Olive oil', 2, 'tbsp'),
      I('Italian seasoning', 1, 'tsp'),
    ],
    steps: ['Season chicken', 'Sear in pan', 'Add garlic & tomatoes', 'Pour cream & simmer', 'Add spinach & parmesan'],
    nutrition: { calories: 420, protein: 38, carbs: 12, fat: 24 },
    category: 'dinner',
    rating: 4.8,
  },
  {
    id: 'avocado-toast-deluxe',
    title: 'Avocado Toast Deluxe',
    description: 'Elevated brunch classic',
    image: 'https://images.unsplash.com/photo-1588137378633-dea1336ce1e2?w=600&q=80',
    minutes: 15,
    prepMinutes: 10,
    servings: 2,
    difficulty: 'Easy',
    tags: ['quick', 'healthy', 'vegetarian', 'mediterranean', 'whole-foods', 'breakfast'],
    ingredients: [
      I('Sourdough bread', 2, 'slices'),
      I('Avocado', 1, 'whole'),
      I('Cherry tomatoes', 100, 'g'),
      I('Feta cheese', 40, 'g'),
      I('Chilli flakes', 0.5, 'tsp'),
      I('Lemon', 0.5, 'whole'),
    ],
    steps: ['Toast bread', 'Mash avocado with lemon', 'Spread on toast', 'Top with tomatoes & feta', 'Sprinkle chilli flakes'],
    nutrition: { calories: 310, protein: 10, carbs: 32, fat: 16 },
    category: 'breakfast',
    rating: 4.5,
  },
  {
    id: 'thai-green-curry-legacy',
    title: 'Thai Green Curry',
    description: 'Aromatic coconut curry',
    image: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=600&q=80',
    minutes: 45,
    prepMinutes: 15,
    servings: 4,
    difficulty: 'Medium',
    tags: ['spicy', 'thai', 'curry', 'high-protein', 'asian', 'dinner'],
    ingredients: [
      I('Green curry paste', 3, 'tbsp'),
      I('Coconut milk', 400, 'ml'),
      I('Chicken thigh', 500, 'g'),
      I('Thai basil', 1, 'handful'),
      I('Bamboo shoots', 150, 'g'),
      I('Fish sauce', 2, 'tbsp'),
      I('Jasmine rice', 300, 'g'),
    ],
    steps: ['Fry curry paste', 'Add coconut milk', 'Add chicken', 'Simmer 20 min', 'Add basil & serve'],
    stepTimers: [null, null, null, 1200, null],
    nutrition: { calories: 380, protein: 28, carbs: 34, fat: 14 },
    category: 'dinner',
    rating: 4.7,
  },
  {
    id: 'berry-smoothie-bowl',
    title: 'Berry Smoothie Bowl',
    description: 'Refreshing & nutritious',
    image: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=600&q=80',
    minutes: 10,
    prepMinutes: 10,
    servings: 1,
    difficulty: 'Easy',
    tags: ['healthy', 'quick', 'vegetarian', 'plant-based', 'whole-foods', 'breakfast'],
    ingredients: [
      I('Mixed berries', 150, 'g'),
      I('Banana', 1, 'whole'),
      I('Greek yoghurt', 150, 'g'),
      I('Granola', 30, 'g'),
      I('Chia seeds', 1, 'tbsp'),
      I('Honey', 1, 'tsp'),
    ],
    steps: ['Blend berries & banana', 'Pour into bowl', 'Top with granola', 'Add chia seeds & honey'],
    nutrition: { calories: 280, protein: 12, carbs: 48, fat: 6 },
    category: 'breakfast',
    rating: 4.6,
  },
  {
    id: 'lemon-herb-salmon-legacy',
    title: 'Lemon Herb Salmon',
    description: 'Light & zesty fillet',
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=600&q=80',
    minutes: 25,
    prepMinutes: 10,
    servings: 2,
    difficulty: 'Easy',
    tags: ['fish', 'healthy', 'high-protein', 'mediterranean', 'low-carb', 'whole-foods', 'pescatarian'],
    ingredients: [
      I('Salmon fillet', 2, 'fillets'),
      I('Lemon', 1, 'whole'),
      I('Fresh dill', 2, 'tbsp'),
      I('Garlic cloves', 2, 'cloves'),
      I('Olive oil', 2, 'tbsp'),
      I('Asparagus', 250, 'g'),
      I('Sea salt', 0.5, 'tsp'),
      I('Black pepper', 0.25, 'tsp'),
    ],
    steps: [
      'Preheat oven to 200°C / 400°F',
      'Season salmon with salt, pepper, minced garlic & dill',
      'Place on lined tray with asparagus, drizzle olive oil',
      'Top with lemon slices, bake 12-15 min',
      'Squeeze fresh lemon juice before serving',
    ],
    stepTimers: [null, null, null, 780, null],
    nutrition: { calories: 350, protein: 34, carbs: 8, fat: 20 },
    category: 'healthy',
    rating: 4.9,
  },
  {
    id: 'chocolate-lava-cake',
    title: 'Chocolate Lava Cake',
    description: 'Indulgent molten centre',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&q=80',
    minutes: 27,
    prepMinutes: 15,
    servings: 2,
    difficulty: 'Medium',
    tags: ['chocolate', 'dessert', 'indulgent'],
    ingredients: [
      I('Dark chocolate', 100, 'g'),
      I('Butter', 80, 'g'),
      I('Eggs', 2, 'whole'),
      I('Sugar', 60, 'g'),
      I('Flour', 30, 'g'),
      I('Vanilla extract', 1, 'tsp'),
    ],
    steps: [
      'Preheat oven to 220°C / 425°F, butter ramekins',
      'Melt chocolate & butter together, stir smooth',
      'Whisk eggs, sugar & vanilla until pale',
      'Fold chocolate mix into eggs, add flour',
      'Pour into ramekins, bake 10-12 min until edges set',
    ],
    stepTimers: [null, 120, 120, null, 660],
    nutrition: { calories: 490, protein: 8, carbs: 42, fat: 32 },
    category: 'dessert',
    rating: 4.9,
  },
  {
    id: 'mediterranean-quinoa-bowl-legacy',
    title: 'Mediterranean Quinoa Bowl',
    description: 'Colourful & wholesome',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80',
    minutes: 25,
    prepMinutes: 10,
    servings: 2,
    difficulty: 'Easy',
    tags: ['healthy', 'vegetarian', 'meal-prep', 'mediterranean', 'plant-based', 'whole-foods', 'lunch'],
    ingredients: [
      I('Quinoa', 150, 'g'),
      I('Cucumber', 1, 'whole'),
      I('Cherry tomatoes', 150, 'g'),
      I('Kalamata olives', 50, 'g'),
      I('Feta', 80, 'g'),
      I('Hummus', 4, 'tbsp'),
      I('Olive oil', 2, 'tbsp'),
    ],
    steps: [
      'Rinse quinoa, cook in salted water 12-15 min',
      'Chop cucumber, halve tomatoes, slice olives',
      'Divide quinoa between bowls',
      'Top with veg, hummus, olives & crumbled feta',
      'Drizzle with olive oil, season to taste',
    ],
    stepTimers: [900, null, null, null, null],
    nutrition: { calories: 340, protein: 14, carbs: 44, fat: 14 },
    category: 'lunch',
    rating: 4.5,
  },
  {
    id: 'spicy-prawn-tacos',
    title: 'Spicy Prawn Tacos',
    description: 'Loaded with fresh salsa',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&q=80',
    minutes: 25,
    prepMinutes: 15,
    servings: 3,
    difficulty: 'Easy',
    tags: ['mexican', 'seafood', 'quick', 'high-protein', 'latin', 'dinner'],
    ingredients: [
      I('King prawns', 400, 'g'),
      I('Corn tortillas', 6, 'whole'),
      I('Lime', 2, 'whole'),
      I('Coriander', 1, 'handful'),
      I('Jalapeño', 1, 'whole'),
      I('Red cabbage', 150, 'g'),
      I('Chilli powder', 1, 'tsp'),
    ],
    steps: [
      'Toss prawns with chilli powder, salt & lime juice',
      'Shred cabbage, slice jalapeño, chop coriander',
      'Heat pan, cook prawns 2-3 min each side',
      'Warm tortillas in a dry pan 30 sec per side',
      'Build tacos with prawns, cabbage, jalapeño & lime',
    ],
    stepTimers: [null, null, 300, 60, null],
    nutrition: { calories: 360, protein: 30, carbs: 38, fat: 10 },
    category: 'dinner',
    rating: 4.7,
  },
];
