import type { CookingRecipe } from './recipeTypes';

const I = (name: string, amount?: number, unit?: string) =>
  amount != null ? `${name} — ${amount}${unit ? ` ${unit}` : ''}` : name;

export const MEXICAN_RECIPES: CookingRecipe[] = [
  {
    id: 'mexican-chilaquiles-verdes',
    title: 'Chilaquiles Verdes',
    description: 'Crisp tortillas simmered in tangy salsa verde with eggs',
    image: 'https://images.unsplash.com/photo-1633372363856-f2fe2669a26e?w=900&q=80',
    minutes: 35,
    prepMinutes: 15,
    servings: 4,
    difficulty: 'Easy',
    tags: ['mexican', 'latin', 'breakfast', 'comfort', 'vegetarian', 'quick'],
    ingredients: [
      I('Corn tortillas', 12, 'whole'),
      I('Tomatillos', 450, 'g'),
      I('Serrano or jalapeño', 2, 'whole'),
      I('White onion', 0.5, 'whole'),
      I('Garlic cloves', 2, 'cloves'),
      I('Chicken or veg stock', 250, 'ml'),
      I('Eggs', 4, 'whole'),
      I('Mexican crema or sour cream', 4, 'tbsp'),
      I('Cotija cheese', 60, 'g'),
      I('Fresh coriander', 1, 'handful'),
    ],
    steps: [
      'Husk tomatillos; boil 5 min until soft; blend with chilli, onion, garlic & salt',
      'Fry salsa in a little oil 5 min; add stock to loosen',
      'Cut or tear tortillas; shallow-fry until crisp, or bake brushed with oil',
      'Fold chips into warm salsa 2–3 min until slightly soft but not mushy',
      'Fry or poach eggs; top chilaquiles with crema, cotija, coriander & eggs',
    ],
    stepTimers: [300, 300, 600, 180, null],
    nutrition: { calories: 385, protein: 16, carbs: 42, fat: 18 },
    category: 'breakfast',
    rating: 4.8,
  },
  {
    id: 'mexican-pozole-rojo',
    title: 'Pozole Rojo',
    description: 'Hominy & pork in a deep red chile broth — fiesta in a bowl',
    image: 'https://images.unsplash.com/photo-1576874762348-f74e25831a92?w=900&q=80',
    minutes: 150,
    prepMinutes: 25,
    servings: 8,
    difficulty: 'Medium',
    tags: ['mexican', 'latin', 'stew', 'comfort', 'batch', 'high-protein'],
    ingredients: [
      I('Pork shoulder (cubed)', 1.2, 'kg'),
      I('White hominy (tins)', 2, 'x 800g'),
      I('Dried guajillo chillies', 6, 'whole'),
      I('Dried ancho chillies', 2, 'whole'),
      I('White onion', 1, 'whole'),
      I('Garlic cloves', 6, 'cloves'),
      I('Mexican oregano', 1, 'tbsp'),
      I('Bay leaves', 2, 'whole'),
      I('Radishes, lime, cabbage', 1, 'set'),
    ],
    steps: [
      'Simmer pork with half an onion, garlic, bay & salt 60–90 min until tender',
      'Toast dried chillies; soak in hot water 15 min; blend smooth',
      'Strain broth; add chilli purée & oregano; simmer 20 min',
      'Stir in drained hominy; cook 25 min more',
      'Serve with shredded cabbage, sliced radish, lime & tostadas',
    ],
    stepTimers: [5400, 900, 1200, 1500, null],
    nutrition: { calories: 420, protein: 32, carbs: 38, fat: 16 },
    category: 'dinner',
    rating: 4.9,
  },
  {
    id: 'mexican-enchiladas-verdes',
    title: 'Chicken Enchiladas Verdes',
    description: 'Rolled tortillas baked in bright tomatillo sauce',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=900&q=80',
    minutes: 55,
    prepMinutes: 20,
    servings: 6,
    difficulty: 'Medium',
    tags: ['mexican', 'latin', 'comfort', 'high-protein', 'dinner', 'batch'],
    ingredients: [
      I('Cooked shredded chicken', 500, 'g'),
      I('Corn tortillas', 12, 'whole'),
      I('Tomatillos', 600, 'g'),
      I('Serrano', 1, 'whole'),
      I('Garlic', 3, 'cloves'),
      I('Mexican crema', 120, 'ml'),
      I('Monterey Jack cheese', 200, 'g'),
      I('White onion', 1, 'whole'),
      I('Fresh coriander', 1, 'handful'),
    ],
    steps: [
      'Roast tomatillos & serrano; blend with garlic, onion, coriander & salt for salsa',
      'Warm tortillas; dip each in salsa, fill with chicken, roll tightly',
      'Pack into baking dish; cover with remaining salsa & cheese',
      'Bake 200°C / 400°F 20 min until bubbling',
      'Drizzle crema; serve with beans or salad',
    ],
    stepTimers: [null, null, null, 1200, null],
    nutrition: { calories: 445, protein: 30, carbs: 36, fat: 22 },
    category: 'dinner',
    rating: 4.7,
  },
  {
    id: 'mexican-huevos-rancheros',
    title: 'Huevos Rancheros',
    description: 'Crispy tortillas, beans, salsa roja & sunny eggs',
    image: 'https://images.unsplash.com/photo-1650330151304-5db3ca9b3b6c?w=900&q=80',
    minutes: 25,
    prepMinutes: 10,
    servings: 2,
    difficulty: 'Easy',
    tags: ['mexican', 'latin', 'breakfast', 'vegetarian', 'quick', 'healthy'],
    ingredients: [
      I('Corn tortillas', 4, 'whole'),
      I('Eggs', 4, 'whole'),
      I('Black beans (refried or whole)', 400, 'g'),
      I('Plum tomatoes', 4, 'whole'),
      I('White onion', 0.5, 'whole'),
      I('Jalapeño', 1, 'whole'),
      I('Garlic', 2, 'cloves'),
      I('Vegetable oil', 2, 'tbsp'),
      I('Avocado', 1, 'whole'),
    ],
    steps: [
      'Char tomatoes, onion, jalapeño; blend with garlic for ranchera salsa; simmer 8 min',
      'Warm beans with a splash of water',
      'Fry tortillas until crisp; keep warm',
      'Fry eggs sunny-side up',
      'Layer tortilla, beans, salsa & egg; top with avocado',
    ],
    stepTimers: [480, null, 180, 240, null],
    nutrition: { calories: 410, protein: 18, carbs: 44, fat: 18 },
    category: 'breakfast',
    rating: 4.6,
  },
  {
    id: 'mexican-sopa-de-tortilla',
    title: 'Sopa de Tortilla',
    description: 'Smoky tomato–chile broth with fried tortilla strips & avocado',
    image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=900&q=80',
    minutes: 45,
    prepMinutes: 15,
    servings: 4,
    difficulty: 'Easy',
    tags: ['mexican', 'latin', 'soup', 'comfort', 'vegetarian', 'healthy'],
    ingredients: [
      I('Plum tomatoes', 6, 'whole'),
      I('Dried pasilla or ancho', 2, 'whole'),
      I('Garlic cloves', 3, 'cloves'),
      I('White onion', 1, 'whole'),
      I('Vegetable stock', 1.2, 'l'),
      I('Corn tortillas', 6, 'whole'),
      I('Avocado', 1, 'whole'),
      I('Mexican crema', 4, 'tbsp'),
      I('Queso fresco', 80, 'g'),
    ],
    steps: [
      'Toast chillies; soak; blend with roasted tomatoes, garlic & onion',
      'Fry paste in oil 3 min; add stock; simmer 20 min',
      'Cut tortillas into strips; fry until crisp',
      'Season soup; divide into bowls',
      'Top with tortilla strips, cubed avocado, crema & cheese',
    ],
    stepTimers: [null, 1200, 300, null, null],
    nutrition: { calories: 280, protein: 8, carbs: 38, fat: 12 },
    category: 'lunch',
    rating: 4.7,
  },
  {
    id: 'mexican-carnitas',
    title: 'Oven Carnitas',
    description: 'Slow-roasted pork shoulder — crisp edges, tender centre',
    image: 'https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?w=900&q=80',
    minutes: 200,
    prepMinutes: 15,
    servings: 8,
    difficulty: 'Medium',
    tags: ['mexican', 'latin', 'high-protein', 'batch', 'comfort', 'dinner'],
    ingredients: [
      I('Pork shoulder (chunked)', 2, 'kg'),
      I('Orange juice', 250, 'ml'),
      I('Lime juice', 60, 'ml'),
      I('Garlic cloves', 8, 'cloves'),
      I('Mexican oregano', 1, 'tbsp'),
      I('Ground cumin', 2, 'tsp'),
      I('Bay leaves', 3, 'whole'),
      I('Salt & black pepper'),
    ],
    steps: [
      'Toss pork with citrus, crushed garlic, oregano, cumin, bay, salt & pepper',
      'Pack in deep roasting dish; cover tightly with foil',
      'Roast 150°C / 300°F ~3 hr until fork-tender',
      'Uncover; shred; return to oven 200°C / 400°F 15–20 min until edges crisp',
      'Serve in tacos with onion, coriander & salsa',
    ],
    stepTimers: [null, null, 10800, 1200, null],
    nutrition: { calories: 385, protein: 34, carbs: 4, fat: 26 },
    category: 'dinner',
    rating: 4.9,
  },
  {
    id: 'mexican-birria-tacos',
    title: 'Birria de Res (Quesabirria Style)',
    description: 'Beef chuck in rich guajillo consomé — perfect for dipping tacos',
    image: 'https://images.unsplash.com/photo-1648071598153-428215dce7bb?w=900&q=80',
    minutes: 180,
    prepMinutes: 30,
    servings: 6,
    difficulty: 'Hard',
    tags: ['mexican', 'latin', 'beef', 'comfort', 'batch', 'high-protein', 'spicy'],
    ingredients: [
      I('Beef chuck roast', 1.5, 'kg'),
      I('Dried guajillo chillies', 8, 'whole'),
      I('Dried ancho chillies', 3, 'whole'),
      I('Chipotle in adobo', 2, 'tbsp'),
      I('White onion', 1, 'whole'),
      I('Garlic bulb', 1, 'whole'),
      I('Beef stock', 1.2, 'l'),
      I('Corn tortillas', 12, 'whole'),
      I('Oaxaca or mozzarella', 200, 'g'),
      I('Apple cider vinegar', 2, 'tbsp'),
    ],
    steps: [
      'Toast chillies; soak; blend with onion, garlic, chipotle, vinegar & spices',
      'Sear beef; add purée & stock; pressure-cook 45 min or braise 2.5 hr',
      'Shred meat; strain broth; season consomé',
      'Dip tortillas in fat/broth; fill with cheese & beef; griddle until crisp',
      'Serve with consomé bowls, lime & onion',
    ],
    stepTimers: [null, 9000, null, 600, null],
    nutrition: { calories: 520, protein: 38, carbs: 32, fat: 28 },
    category: 'dinner',
    rating: 4.9,
  },
  {
    id: 'mexican-chiles-rellenos',
    title: 'Chiles Rellenos',
    description: 'Roasted poblanos stuffed with cheese, light batter, tomato salsa',
    image: 'https://images.unsplash.com/photo-1676081986290-ac79c2968c3f?w=900&q=80',
    minutes: 70,
    prepMinutes: 25,
    servings: 4,
    difficulty: 'Hard',
    tags: ['mexican', 'latin', 'vegetarian', 'comfort', 'dinner'],
    ingredients: [
      I('Large poblano peppers', 6, 'whole'),
      I('Oaxaca or Monterey Jack', 300, 'g'),
      I('Eggs', 4, 'whole'),
      I('Plain flour', 60, 'g'),
      I('Plum tomatoes', 4, 'whole'),
      I('White onion', 0.5, 'whole'),
      I('Garlic', 2, 'cloves'),
      I('Vegetable oil', 400, 'ml'),
    ],
    steps: [
      'Blacken poblanos over flame; steam in bag; peel carefully',
      'Cut slit; remove seeds; stuff with cheese; secure with toothpicks',
      'Whip egg whites; fold in yolks for batter; dust chiles in flour then coat',
      'Shallow-fry until golden; drain',
      'Simmer quick salsa roja; spoon over chiles to serve',
    ],
    stepTimers: [600, null, null, 480, 600],
    nutrition: { calories: 465, protein: 22, carbs: 28, fat: 30 },
    category: 'dinner',
    rating: 4.6,
  },
  {
    id: 'mexican-esquites',
    title: 'Esquites',
    description: 'Warm sweetcorn cup with mayo, lime, chilli & cotija',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=900&q=80',
    minutes: 20,
    prepMinutes: 10,
    servings: 4,
    difficulty: 'Easy',
    tags: ['mexican', 'latin', 'street-food', 'vegetarian', 'quick', 'side'],
    ingredients: [
      I('Sweetcorn kernels', 600, 'g'),
      I('Butter', 20, 'g'),
      I('Mayonnaise', 3, 'tbsp'),
      I('Lime', 2, 'whole'),
      I('Cotija cheese', 80, 'g'),
      I('Chilli powder or Tajín', 1, 'tsp'),
      I('Fresh coriander', 2, 'tbsp'),
    ],
    steps: [
      'Cook corn in butter until lightly charred in spots',
      'Stir in a splash of water; simmer 3 min',
      'Spoon into cups; mix mayo with lime juice',
      'Top with mayo mix, cotija, chilli & coriander',
    ],
    stepTimers: [300, 180, null, null],
    nutrition: { calories: 240, protein: 8, carbs: 32, fat: 10 },
    category: 'lunch',
    rating: 4.5,
  },
  {
    id: 'mexican-tamales',
    title: 'Tamales de Pollo',
    description: 'Masa harina parcels steamed in corn husks with red salsa chicken',
    image: 'https://images.unsplash.com/photo-1613514785940-daed07799d9b?w=900&q=80',
    minutes: 180,
    prepMinutes: 60,
    servings: 16,
    difficulty: 'Hard',
    tags: ['mexican', 'latin', 'comfort', 'batch', 'high-protein', 'meal-prep'],
    ingredients: [
      I('Masa harina', 500, 'g'),
      I('Lard or butter', 200, 'g'),
      I('Chicken stock (warm)', 600, 'ml'),
      I('Baking powder', 1, 'tbsp'),
      I('Cooked shredded chicken', 500, 'g'),
      I('Dried corn husks', 20, 'whole'),
      I('Red salsa (thick)', 300, 'ml'),
    ],
    steps: [
      'Soak corn husks in hot water 30 min',
      'Beat lard until fluffy; gradually beat in masa, baking powder & stock to soft dough',
      'Spread dough on husks; add chicken & salsa; fold & tie',
      'Stand upright in steamer; steam 70–90 min until masa pulls cleanly from husk',
      'Rest 10 min before eating',
    ],
    stepTimers: [1800, null, null, 4800, 600],
    nutrition: { calories: 310, protein: 14, carbs: 36, fat: 14 },
    category: 'dinner',
    rating: 4.8,
  },
];
