import type { CookingRecipe } from './recipeTypes';

/** Curated tab recipes (original cooking tab expansion) with per-serving nutrition estimates. */
export const TAB_RECIPES: CookingRecipe[] = [
  {
    id: 'grilled-chicken-bowl',
    title: 'Grilled Chicken Bowl',
    description: 'Juicy chicken with avocado, greens, and a bright herb dressing.',
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=900&q=80',
    minutes: 22,
    prepMinutes: 8,
    servings: 2,
    difficulty: 'Easy',
    tags: ['low-carb', 'high-protein', 'quick', 'healthy', 'gluten-free'],
    ingredients: ['Chicken breast 400g', 'Avocado 1', 'Mixed greens', 'Olive oil', 'Lemon', 'Garlic 2 cloves', 'Salt & pepper'],
    steps: [
      'Season chicken and rest 10 minutes.',
      'Grill or pan-sear chicken until 74°C internal.',
      'Slice avocado; toss greens with lemon, oil, and crushed garlic.',
      'Slice chicken, plate over greens, top with avocado.',
    ],
    stepTimers: [600, 480, null, null],
    stepHints: [
      'Salt lightly on both sides so the meat stays juicy when searing.',
      'Use medium-high heat; flip once the edges turn opaque.',
      'Dress greens lightly first so they stay crisp.',
      'Slice across the grain for the most tender bites.',
    ],
    nutrition: { calories: 485, protein: 44, carbs: 14, fat: 28 },
    category: 'lunch',
    rating: 4.7,
  },
  {
    id: 'garlic-salmon',
    title: 'Garlic Butter Salmon',
    description: 'Crisp edges, tender centre, lemon-garlic butter.',
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=700&q=80',
    minutes: 18,
    prepMinutes: 5,
    servings: 2,
    difficulty: 'Easy',
    tags: ['low-carb', 'keto-friendly', 'high-protein', 'quick', 'healthy', 'pescatarian'],
    ingredients: ['Salmon fillets 500g', 'Butter 40g', 'Garlic 4 cloves', 'Lemon', 'Parsley', 'Salt'],
    steps: [
      'Pat salmon dry; season skin and flesh.',
      'Sear skin-side in hot pan 4 minutes.',
      'Flip; add butter, garlic, lemon zest; baste 3–4 minutes.',
      'Finish with lemon juice and parsley.',
    ],
    stepTimers: [null, 240, 240, null],
    stepHints: [
      'Dry skin = crisp skin. Moisture causes steaming instead of sear.',
      'Press gently for the first minute so the skin contacts the pan.',
      'Tilt the pan and spoon foaming butter over the fillet.',
      'A squeeze of acid at the end lifts all the rich flavours.',
    ],
    nutrition: { calories: 395, protein: 36, carbs: 4, fat: 26 },
    category: 'dinner',
    rating: 4.8,
  },
  {
    id: 'beef-broccoli',
    title: 'Beef & Broccoli Stir Fry',
    description: 'Savory stir-fry with tender strips and crisp broccoli.',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=700&q=80',
    minutes: 25,
    prepMinutes: 12,
    servings: 3,
    difficulty: 'Medium',
    tags: ['high-protein', 'quick', 'asian', 'comfort'],
    ingredients: ['Beef sirloin 450g', 'Broccoli 400g', 'Soy sauce', 'Oyster sauce', 'Ginger', 'Cornflour', 'Oil'],
    steps: [
      'Slice beef; toss with cornflour and soy.',
      'Blanch broccoli 2 minutes; drain.',
      'Stir-fry beef in batches; set aside.',
      'Fry ginger, return beef and broccoli, glaze with sauces.',
    ],
    stepTimers: [null, 120, null, 180],
    stepHints: [
      'Velveting with cornflour keeps strips tender in the wok.',
      'Shock broccoli in cold water if you want extra crunch.',
      'Crowding the pan steams meat — work in batches.',
      'High heat at the end glazes the sauce onto every piece.',
    ],
    nutrition: { calories: 410, protein: 36, carbs: 18, fat: 20 },
    category: 'dinner',
    rating: 4.6,
  },
  {
    id: 'zoodle-pesto',
    title: 'Zucchini Noodles & Pesto',
    description: 'Light “pasta” with basil pesto and cherry tomatoes.',
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=700&q=80',
    minutes: 16,
    prepMinutes: 10,
    servings: 2,
    difficulty: 'Easy',
    tags: ['low-carb', 'keto-friendly', 'vegetarian', 'quick', 'healthy'],
    ingredients: ['Zucchini 3 large', 'Basil pesto 4 tbsp', 'Cherry tomatoes', 'Parmesan', 'Pine nuts'],
    steps: [
      'Spiralize zucchini; pat very dry.',
      'Warm pesto in a wide pan.',
      'Toss zoodles 90 seconds only.',
      'Top with tomatoes, parmesan, and toasted pine nuts.',
    ],
    stepTimers: [null, 60, 90, null],
    stepHints: [
      'Excess water makes zoodles soggy — squeeze in a towel if needed.',
      'Low heat for pesto keeps basil oils bright.',
      'Stop early; residual heat continues cooking.',
      'Toast pine nuts in a dry pan until golden for deeper flavour.',
    ],
    nutrition: { calories: 315, protein: 10, carbs: 14, fat: 26 },
    category: 'lunch',
    rating: 4.5,
  },
  {
    id: 'cauliflower-rice-shrimp',
    title: 'Spicy Shrimp & Cauliflower Rice',
    description: 'High heat shrimp with riced cauliflower and lime.',
    image: 'https://images.unsplash.com/photo-1516684732162-798a0062be99?w=600&q=80',
    minutes: 18,
    prepMinutes: 8,
    servings: 2,
    difficulty: 'Easy',
    tags: ['low-carb', 'high-protein', 'quick', 'keto-friendly', 'pescatarian'],
    ingredients: ['Shrimp 400g', 'Cauliflower rice 500g', 'Chili flakes', 'Lime', 'Cilantro', 'Garlic'],
    steps: [
      'Dry shrimp; season with chili, salt, garlic.',
      'Pan-sear shrimp 2 minutes per side; set aside.',
      'Stir-fry cauliflower rice until lightly golden.',
      'Fold in shrimp, lime juice, and cilantro.',
    ],
    stepTimers: [null, 240, 300, null],
    stepHints: [
      'Pat shrimp very dry for a quick sear instead of stewing.',
      'Remove as soon as pink — they continue cooking off heat.',
      'Let cauliflower rice sit undisturbed to pick up colour.',
      'Finish with lime off heat so the aroma stays fresh.',
    ],
    nutrition: { calories: 295, protein: 34, carbs: 16, fat: 11 },
    category: 'dinner',
    rating: 4.7,
  },
  {
    id: 'jollof-inspired',
    title: 'One-Pan Tomato Rice & Chicken',
    description: 'West-African–inspired spiced tomato rice with chicken thighs.',
    image: 'https://images.unsplash.com/photo-1604329760661-e71dc79f8f26?w=800&q=80',
    minutes: 55,
    prepMinutes: 15,
    servings: 4,
    difficulty: 'Medium',
    tags: ['nigerian', 'west-african', 'african', 'jollof', 'comfort', 'batch'],
    ingredients: ['Chicken thighs 6', 'Long-grain rice 300g', 'Tomato paste', 'Onions 2', 'Bell pepper', 'Thyme', 'Stock'],
    steps: [
      'Brown chicken; set aside.',
      'Cook onions and peppers; stir in tomato paste and spices.',
      'Add rice and stock; nestle chicken on top.',
      'Simmer covered until rice is tender.',
    ],
    stepTimers: [420, 360, null, 1500],
    stepHints: [
      'Colour on the chicken adds depth to the finished dish.',
      'Cook tomato paste until it darkens slightly — raw paste tastes flat.',
      'Keep the liquid ratio tight; you can add a splash more if needed.',
      'No peeking for the first 15 minutes of simmer so rice steams evenly.',
    ],
    nutrition: { calories: 515, protein: 34, carbs: 52, fat: 18 },
    category: 'dinner',
    rating: 4.8,
  },
  {
    id: 'chana-masala',
    title: 'Chana Masala',
    description: 'Tomato chickpea curry — great with rice or flatbread.',
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&q=80',
    minutes: 35,
    prepMinutes: 10,
    servings: 4,
    difficulty: 'Easy',
    tags: ['indian', 'curry', 'masala', 'vegetarian', 'plant-based', 'healthy', 'batch'],
    ingredients: ['Chickpeas 2 cans', 'Tomatoes 400g', 'Onion', 'Ginger', 'Garam masala', 'Cumin', 'Oil'],
    steps: [
      'Soften onion; add ginger and dry spices until fragrant.',
      'Add tomatoes; simmer 10 minutes.',
      'Stir in chickpeas; simmer 15 minutes.',
      'Adjust salt; finish with cilantro.',
    ],
    stepTimers: [240, 600, 900, null],
    stepHints: [
      'Bloom spices in oil — you should smell them before adding liquid.',
      'Break tomatoes with a spoon as they soften.',
      'Mash a few chickpeas against the pan to thicken the gravy.',
      'Balance with salt, lemon, or a pinch of sugar if acidic.',
    ],
    nutrition: { calories: 335, protein: 13, carbs: 48, fat: 11 },
    category: 'dinner',
    rating: 4.7,
  },
  {
    id: 'miso-salmon-bowl',
    title: 'Miso Glazed Salmon Bowl',
    description: 'Umami glaze with steamed greens and short grain rice.',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80',
    minutes: 28,
    prepMinutes: 10,
    servings: 2,
    difficulty: 'Medium',
    tags: ['japanese', 'sushi', 'healthy', 'high-protein', 'pescatarian'],
    ingredients: ['Salmon 400g', 'White miso', 'Mirin', 'Soy sauce', 'Sesame', 'Bok choy', 'Rice'],
    steps: [
      'Whisk miso, mirin, and soy; coat salmon.',
      'Bake or broil salmon until caramelised.',
      'Steam greens; cook rice.',
      'Plate rice, greens, and salmon; sprinkle sesame.',
    ],
    stepTimers: [null, 480, 600, null],
    stepHints: [
      'Thin miso glaze with a splash of water so it does not burn instantly.',
      'Broil on an upper rack for faster colour — watch closely.',
      'Shock greens in ice water if you want them vividly green.',
      'Toast sesame seeds briefly for nuttier aroma.',
    ],
    nutrition: { calories: 525, protein: 30, carbs: 52, fat: 20 },
    category: 'dinner',
    rating: 4.7,
  },
  {
    id: 'kimchi-fried-rice',
    title: 'Kimchi Fried Rice',
    description: 'Fermented kick with egg and scallions.',
    image: 'https://images.unsplash.com/photo-1590301157890-4810ed352e47?w=800&q=80',
    minutes: 20,
    prepMinutes: 8,
    servings: 2,
    difficulty: 'Easy',
    tags: ['korean', 'kimchi', 'k-food', 'comfort', 'quick'],
    ingredients: ['Day-old rice 500g', 'Kimchi 150g', 'Eggs 2', 'Scallions', 'Sesame oil', 'Gochujang'],
    steps: [
      'Chop kimchi; reserve some brine.',
      'Stir-fry kimchi; add rice and gochujang.',
      'Push rice aside; scramble eggs in the pan.',
      'Fold together; finish with sesame oil and scallions.',
    ],
    stepTimers: [null, 180, 120, null],
    stepHints: [
      'Brine adds tang — add a spoonful if the rice feels dry.',
      'Day-old rice fries best; fresh rice can turn mushy.',
      'Scramble eggs gently so you still see curds.',
      'Sesame oil is a finisher — heat kills its aroma.',
    ],
    nutrition: { calories: 385, protein: 14, carbs: 62, fat: 10 },
    category: 'lunch',
    rating: 4.6,
  },
  {
    id: 'tacos-carne',
    title: 'Skillet Beef Tacos',
    description: 'Weeknight tacos with lime and quick salsa.',
    image: 'https://images.unsplash.com/photo-1565299585323-38174c0b5e39?w=800&q=80',
    minutes: 24,
    prepMinutes: 10,
    servings: 4,
    difficulty: 'Easy',
    tags: ['mexican', 'latin', 'high-protein', 'comfort', 'quick'],
    ingredients: ['Beef mince 500g', 'Taco spices', 'Tortillas', 'Lime', 'Onion', 'Tomato', 'Cheese'],
    steps: [
      'Brown beef; drain excess fat.',
      'Add spices and a splash of water; simmer 5 minutes.',
      'Dice quick salsa with tomato, onion, lime.',
      'Warm tortillas; assemble tacos.',
    ],
    stepTimers: [300, 300, null, 60],
    stepHints: [
      'Deep brown fond on beef = deeper taco flavour.',
      'Simmer until the pan looks almost dry but not burnt.',
      'Season salsa with salt after tasting — lime varies in acidity.',
      'Char tortillas over a flame if you like smoky edges.',
    ],
    nutrition: { calories: 455, protein: 26, carbs: 36, fat: 22 },
    category: 'dinner',
    rating: 4.5,
  },
  {
    id: 'feijoada-lite',
    title: 'Black Bean & Sausage Stew',
    description: 'Brazilian-inspired hearty stew (lighter weeknight version).',
    image: 'https://images.unsplash.com/photo-1596797038530-2c107229498b?w=800&q=80',
    minutes: 45,
    prepMinutes: 12,
    servings: 4,
    difficulty: 'Medium',
    tags: ['brazilian', 'latin', 'high-protein', 'batch', 'comfort'],
    ingredients: ['Black beans 2 cans', 'Smoked sausage 300g', 'Onion', 'Bay leaves', 'Garlic', 'Stock'],
    steps: [
      'Render sausage; remove.',
      'Cook onion and garlic; add beans and stock.',
      'Simmer 25 minutes; mash some beans for body.',
      'Return sausage; season and serve.',
    ],
    stepTimers: [240, null, 1500, 180],
    stepHints: [
      'Render slowly — browned sausage fat carries flavour.',
      'Scrape the fond when adding liquid.',
      'Mash just a third of beans for a creamy texture.',
      'Finish acidity with vinegar or lime if it tastes flat.',
    ],
    nutrition: { calories: 395, protein: 22, carbs: 38, fat: 16 },
    category: 'dinner',
    rating: 4.6,
  },
  {
    id: 'greek-salmon-salad',
    title: 'Greek Salmon Salad',
    description: 'Mediterranean bowl with feta, olives, and cucumber.',
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800&q=80',
    minutes: 26,
    prepMinutes: 12,
    servings: 2,
    difficulty: 'Easy',
    tags: ['mediterranean', 'healthy', 'low-carb', 'high-protein', 'pescatarian', 'keto-friendly'],
    ingredients: ['Salmon 350g', 'Cucumber', 'Tomatoes', 'Olives', 'Feta', 'Oregano', 'Olive oil'],
    steps: [
      'Bake or pan-sear salmon; flake.',
      'Chop salad vegetables.',
      'Dress with oil, lemon, oregano.',
      'Top with salmon and feta.',
    ],
    stepTimers: [420, null, null, null],
    stepHints: [
      'Cook salmon to medium — it flakes easily but stays moist.',
      'Uniform cucumber/tomato sizes make every forkful balanced.',
      'Dress lightly; you can always add more.',
      'Feta is salty — taste before adding extra salt.',
    ],
    nutrition: { calories: 445, protein: 34, carbs: 14, fat: 30 },
    category: 'lunch',
    rating: 4.8,
  },
  {
    id: 'overnight-oats-batch',
    title: 'Batch Overnight Oats',
    description: 'Prep 4 jars for busy mornings.',
    image: 'https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=800&q=80',
    minutes: 15,
    prepMinutes: 15,
    servings: 4,
    difficulty: 'Easy',
    tags: ['batch', 'meal-prep', 'vegetarian', 'healthy', 'whole-foods'],
    ingredients: ['Rolled oats 400g', 'Milk or alt milk', 'Chia 4 tbsp', 'Yogurt', 'Berries', 'Maple syrup'],
    steps: [
      'Mix oats, chia, milk, and yogurt.',
      'Divide into jars; sweeten lightly.',
      'Refrigerate overnight.',
      'Top with berries before eating.',
    ],
    stepTimers: [null, null, null, null],
    stepHints: [
      'Chia thickens overnight — add extra milk if you prefer looser oats.',
      'Leave headspace in jars so you can stir easily.',
      '8+ hours sets the texture; 4 hours works in a pinch.',
      'Warm berries slightly if you want jammy swirls.',
    ],
    nutrition: { calories: 305, protein: 12, carbs: 46, fat: 8 },
    category: 'breakfast',
    rating: 4.6,
  },
  {
    id: 'lentil-soup',
    title: 'Red Lentil Soup',
    description: 'Velvety soup — freezes well.',
    image: 'https://images.unsplash.com/photo-1547592166-23ab45744aca?w=800&q=80',
    minutes: 40,
    prepMinutes: 10,
    servings: 4,
    difficulty: 'Easy',
    tags: ['vegetarian', 'plant-based', 'batch', 'comfort', 'healthy', 'whole-foods'],
    ingredients: ['Red lentils 300g', 'Carrot', 'Onion', 'Cumin', 'Turmeric', 'Stock 1L', 'Lemon'],
    steps: [
      'Sweat onion and carrot.',
      'Add spices; stir in lentils and stock.',
      'Simmer 25 minutes; blend partly if desired.',
      'Finish with lemon.',
    ],
    stepTimers: [300, null, 1500, null],
    stepHints: [
      'Low heat sweat — translucent, not browned (unless you prefer deeper flavour).',
      'Toast cumin until aromatic before adding liquid.',
      'Blend half for silkiness while keeping some lentils whole.',
      'Acid at the end lifts earthy spices.',
    ],
    nutrition: { calories: 245, protein: 14, carbs: 38, fat: 4 },
    category: 'healthy',
    rating: 4.7,
  },
  {
    id: 'steak-salad',
    title: 'Steak & Arugula Salad',
    description: 'Fast high-protein dinner with mustard vinaigrette.',
    image: 'https://images.unsplash.com/photo-1558030006-450675393462?w=800&q=80',
    minutes: 22,
    prepMinutes: 8,
    servings: 2,
    difficulty: 'Medium',
    tags: ['high-protein', 'low-carb', 'keto-friendly', 'quick', 'healthy'],
    ingredients: ['Steak 400g', 'Arugula', 'Cherry tomatoes', 'Dijon', 'Red wine vinegar', 'Oil'],
    steps: [
      'Season steak; sear to preference.',
      'Rest 5 minutes; slice thin.',
      'Whisk mustard vinaigrette.',
      'Toss arugula and tomatoes; top with steak.',
    ],
    stepTimers: [null, 300, null, null],
    stepHints: [
      'Dry steak + hot pan = crust. Oil the steak, not always the pan.',
      'Resting lets juices settle — slicing early loses moisture.',
      'Emulsify vinaigrette with a slow stream of oil.',
      'Dress greens right before serving so they stay perky.',
    ],
    nutrition: { calories: 425, protein: 38, carbs: 8, fat: 26 },
    category: 'dinner',
    rating: 4.7,
  },
  {
    id: 'shakshuka',
    title: 'Shakshuka',
    description: 'Eggs poached in spiced tomato sauce — one pan.',
    image: 'https://images.unsplash.com/photo-1595295333158-4742f28fbd85?w=800&q=80',
    minutes: 30,
    prepMinutes: 10,
    servings: 3,
    difficulty: 'Easy',
    tags: ['vegetarian', 'comfort', 'healthy', 'mediterranean', 'quick'],
    ingredients: ['Eggs 4–6', 'Crushed tomatoes 800g', 'Bell pepper', 'Cumin', 'Paprika', 'Feta', 'Bread'],
    steps: [
      'Cook peppers and spices in oil.',
      'Add tomatoes; simmer 12 minutes.',
      'Make wells; crack eggs; cover until set.',
      'Crumble feta; serve with bread.',
    ],
    stepTimers: [180, 720, 600, null],
    stepHints: [
      'Soften peppers before tomatoes to build sweetness.',
      'Reduce tomatoes until the oil separates slightly.',
      'Low heat for eggs — whites set before yolks overcook.',
      'Crusty bread is ideal for scooping.',
    ],
    nutrition: { calories: 285, protein: 15, carbs: 28, fat: 14 },
    category: 'breakfast',
    rating: 4.8,
  },
  {
    id: 'thai-green-curry',
    title: 'Thai Green Curry (Chicken)',
    description: 'Aromatic coconut curry in one pot.',
    image: 'https://images.unsplash.com/photo-1455619450894-d5a4b16f9c5a?w=800&q=80',
    minutes: 32,
    prepMinutes: 10,
    servings: 4,
    difficulty: 'Medium',
    tags: ['asian', 'high-protein', 'comfort'],
    ingredients: ['Green curry paste', 'Coconut milk 2 cans', 'Chicken 500g', 'Thai basil', 'Fish sauce', 'Sugar'],
    steps: [
      'Fry paste until fragrant.',
      'Add coconut milk; simmer chicken.',
      'Season with fish sauce and palm sugar.',
      'Stir in basil at the end.',
    ],
    stepTimers: [120, 900, null, null],
    stepHints: [
      'Split thick coconut cream to fry paste if you want extra richness.',
      'Simmer chicken through — cut a thick piece to check.',
      'Balance salty (fish sauce) with sweet (sugar) gradually.',
      'Basil wilts instantly — fold off heat.',
    ],
    nutrition: { calories: 385, protein: 28, carbs: 12, fat: 26 },
    category: 'dinner',
    rating: 4.7,
  },
  {
    id: 'sheet-pan-fajitas',
    title: 'Sheet-Pan Chicken Fajitas',
    description: 'Hands-off roasting — great for meal prep.',
    image: 'https://images.unsplash.com/photo-1594221708779-94832f4320d1?w=800&q=80',
    minutes: 35,
    prepMinutes: 12,
    servings: 4,
    difficulty: 'Easy',
    tags: ['mexican', 'latin', 'batch', 'meal-prep', 'high-protein'],
    ingredients: ['Chicken strips 600g', 'Peppers 3', 'Onions 2', 'Fajita spice', 'Oil', 'Tortillas'],
    steps: [
      'Toss everything on a sheet pan.',
      'Roast at 220°C for 22–26 minutes.',
      'Char under broiler optional.',
      'Serve with warm tortillas.',
    ],
    stepTimers: [null, 1440, 120, 60],
    stepHints: [
      'Single layer on the sheet — overlap steams instead of roasts.',
      'Flip chicken halfway for even colour.',
      'Broiler is fast — stay nearby.',
      'Wrap tortillas in foil while hot.',
    ],
    nutrition: { calories: 455, protein: 36, carbs: 42, fat: 16 },
    category: 'dinner',
    rating: 4.6,
  },
  {
    id: 'buddha-bowl',
    title: 'Rainbow Buddha Bowl',
    description: 'Grains, roasted veg, tahini drizzle.',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80',
    minutes: 35,
    prepMinutes: 12,
    servings: 2,
    difficulty: 'Easy',
    tags: ['vegetarian', 'plant-based', 'healthy', 'whole-foods', 'meal-prep'],
    ingredients: ['Quinoa', 'Sweet potato', 'Chickpeas', 'Kale', 'Tahini', 'Lemon', 'Pumpkin seeds'],
    steps: [
      'Roast chickpeas and sweet potato.',
      'Cook quinoa; massage kale with lemon.',
      'Whisk tahini sauce.',
      'Assemble bowls; drizzle sauce; sprinkle seeds.',
    ],
    stepTimers: [1500, 720, null, null],
    stepHints: [
      'Dry chickpeas roast crispier — rinse then dry well.',
      'Massaging kale softens it without cooking.',
      'Thin tahini sauce with warm water until it ribbons.',
      'Keep components separate until plating for pretty layers.',
    ],
    nutrition: { calories: 395, protein: 14, carbs: 52, fat: 15 },
    category: 'lunch',
    rating: 4.6,
  },
  {
    id: 'egg-muffins',
    title: 'Egg & Veg Muffins',
    description: 'Protein grab-and-go — freeze a dozen.',
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800&q=80',
    minutes: 30,
    prepMinutes: 12,
    servings: 6,
    difficulty: 'Easy',
    tags: ['batch', 'meal-prep', 'keto-friendly', 'high-protein', 'low-carb', 'quick'],
    ingredients: ['Eggs 10', 'Spinach', 'Feta', 'Bell pepper', 'Salt', 'Paprika'],
    steps: [
      'Whisk eggs with salt and paprika.',
      'Fold chopped veg and cheese.',
      'Bake in muffin tin at 180°C for 18–22 minutes.',
      'Cool; refrigerate or freeze.',
    ],
    stepTimers: [null, null, 1200, null],
    stepHints: [
      'Whisk until foamy for fluffier muffins.',
      'Squeeze moisture from spinach if using frozen.',
      'Fill cups ¾ — they puff as they bake.',
      'Cool 5 minutes in tin so they release cleanly.',
    ],
    nutrition: { calories: 175, protein: 14, carbs: 4, fat: 11 },
    category: 'breakfast',
    rating: 4.5,
  },
];
